name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create TypewriterEffect component
        run: |
          mkdir -p components/ui
          cat > components/ui/TypewriterEffect.js << 'EOF'
          import React, { useState, useEffect } from 'react';

          export const TypewriterEffect = ({ text, className, speed = 70, delay = 0, onComplete }) => {
            const [displayText, setDisplayText] = useState('');
            const [currentIndex, setCurrentIndex] = useState(0);
            const [isComplete, setIsComplete] = useState(false);

            useEffect(() => {
              if (delay > 0) {
                const delayTimer = setTimeout(() => {
                  startTyping();
                }, delay);
                
                return () => clearTimeout(delayTimer);
              } else {
                startTyping();
              }
              
              function startTyping() {
                if (currentIndex < text.length) {
                  const timeout = setTimeout(() => {
                    setDisplayText(prev => prev + text[currentIndex]);
                    setCurrentIndex(prevIndex => prevIndex + 1);
                  }, speed);
                  
                  return () => clearTimeout(timeout);
                } else if (!isComplete) {
                  setIsComplete(true);
                  if (onComplete) onComplete();
                }
              }
            }, [currentIndex, delay, isComplete, onComplete, speed, text]);
            
            return (
              <span className={className}>
                {displayText}
                {!isComplete && (
                  <span className="typing-cursor">|</span>
                )}
              </span>
            );
          };

          export default TypewriterEffect;
          EOF

      - name: Fix Hero component import
        run: |
          if grep -q "import TypewriterEffect" components/Hero.js; then
            sed -i 's|import .*TypewriterEffect.*|import TypewriterEffect from "./ui/TypewriterEffect";|' components/Hero.js
          fi

      - name: Install gh-pages
        run: npm install gh-pages --save-dev

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages